plugins {
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'application'
    id 'com.jwavez.java-conventions'
}

apply {
    'java'
    'io.spring.dependency-management'
}

ext {
    jacksonVersion = '2.11.4'
    commonsCliVersion = '1.4'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of("${javaVersion}")
    }
}

jar {
    duplicatesStrategy = "exclude"
    manifest {
        attributes(
                "Implementation-Title": "JWaveZ Products",
                "Implementation-Version": archiveVersion,
                "Main-Class": "com.rposcro.jwavez.products.JWaveZProducts"
        )
    }
}

dependencies {
    implementation project(':jwavez-core')

    implementation "org.springframework.boot:spring-boot-starter"

    implementation "commons-cli:commons-cli:${commonsCliVersion}"

    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:${jacksonVersion}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
}
