plugins {
    id 'java-library'
    id 'com.jwavez.java-conventions'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of("${javaVersion}")
    }
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation 'org.reflections:reflections:0.10.2'
}

description = 'jwavez-core'
